### ISSUE TITLE
NullPointerException when trying to show FilterDialogFragment

### ISSUE THREAD

**Issue by forceporquillo** [firebase/friendlyeats-android#113]
It Throws an error when I re-open a FilterDialogFragment, this occurs when I hit **Add Random Items** then clicking back again the filter dialog.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.firebase.example.fireeats, PID: 20068
    java.lang.IllegalStateException: Fragment already added: FilterDialogFragment{4c008a3} (b144417e-7fc0-4453-99dc-02586918d39d) FilterDialog}
        at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67)
        at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1563)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by samtstern** [comment]
@forceporquillo thanks for reporting this, seems like a bug to me.
