### ISSUE TITLE
" Jibe SDK Service not available" when running app

### ISSUE THREAD

**Issue by CaptainRock** [firebase/friendlyeats-android#137]
2021-10-29 14:31:04.158 10248-10274/? E/Bugle: RcsUtils. Error getting default configuration value for fallback setting
2021-10-29 14:31:04.158 10248-10274/? E/Bugle: com.google.android.rcs.client.e: Jibe SDK Service not available. Is the Jibe SDK service running? Did you call connect() and wait for the notification before calling an API function?
        at com.google.android.rcs.client.a.c(SourceFile:76)
        at com.google.android.rcs.client.profile.RcsProfileService.getRcsConfig(SourceFile:67)
        at com.google.android.apps.messaging.shared.sms.al.i(SourceFile:772)
        at com.google.android.apps.messaging.shared.analytics.RecurringTelemetryUploaderAction.doBackgroundWork(SourceFile:208)
        at com.google.android.apps.messaging.shared.datamodel.action.ActionExecutorImpl$BackgroundWorkerRunnable.run(SourceFile:12)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at com.google.android.apps.messaging.shared.datamodel.action.c.run(SourceFile:10)

**Comment by thatfiredev** [comment]
@CaptainRock is this error related to the friendlyeats codelab? If so, can you describe at what step you found this error?

**Comment by thatfiredev** [comment]
Closing this as there's not enough information to reproduce the issue.

@CaptainRock feel free to re-open if you're still facing the issue.
